### ISSUE TITLE
Investigate performance and possible optimizations

### ISSUE THREAD

**Issue by maxwellevin** [tsdat/tsdat#12]
Tsdat is starting to grow and we have a number of projects using it for large-scale data processing, which means that we need to start thinking more critically about optimizing performance so that these pipelines can run more efficiently. 

This task is to use a profiling tool (such as [pyinstrument](https://github.com/joerick/pyinstrument)) to better understand where the bottlenecks in the existing pipelines are so that we can target optimization efforts there for the greatest impact.

**Comment by maxwellevin** [comment]
@jmcvey3 any updates on this?

**Comment by jmcvey3** [comment]
> @jmcvey3 any updates on this?

Not yet.

**Comment by jmcvey3** [comment]
Speed is primarily affected by QC functions, which are imported from the act-atmos package, and is directly related to the number of variables being run through quality control.
