### ISSUE TITLE
Allow or encode data standards from multiple industries

### ISSUE THREAD

**Issue by jmcvey3** [tsdat/tsdat#132]
**Is your feature request related to a problem? Please describe.**
While standard variable names are left up to the user to follow the applicable standards, some standards require a dataset to have specific global or local keywords. Currently the "units" attribute is the only required local keyword, but there are several global attributes hardcoded in the validation schema in both the "tsdat" and "pipeline template" repos. Some of these attributes are used to form the standardized datatset's filename, while others are useful for describing the data. These attributes change depending on the standards used.

**Describe the solution you'd like**
The easiest solution may be to hardcode multiple validation schema for a selected data standard. The standards utilized by NOAA water level stations around the US (Integrated Ocean Observing System, IOOS) have a long list of metadata for tide gauge stations on the system network, as shown under "Additional Context". 

Similarly to most standards, IOOS has a "required" list and a "nice to have" list of attributes. A good option may be to provide a template that lists all attributes and requires all in the "required" list.

A drawback to the hardcoding approach is that standards get updated from time to time, so one would have to manually keep track of updates.

**Additional context**

```
# https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-2.html
# https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3

# Dataset Description
conventions: "CD-1.6, ACDD-1.3, IOOS-1.2"
featureType: timeseries
id: MCRLdata_TideGauge
infoURL: https://www.osti.gov/biblio/1842840
license: Freely Distributed
naming_authority: gov.pnnl.sequim
standard_name_vocabulary: CF Standard Name Table v79
title: MCRLdata at PNNL-Sequim - Tide Gauge
# TODO: Change to "Summary" to meet standards
description: "A Nile YSI Micropilot FMR51 was deployed on the Marine and Coastal Research Laboratory (MCRL) 
pier at the Pacific Northwest National Laboratory (PNNL) campus in Sequim, Washington. The instrument 
emits continuous, non-contact microwave transmission to measure distance to the water surface (meters), 
which allow measurement of tidal cycles. This deployment is part of the MCRLdata project to establish 
long-term marine monitoring at the PNNL-Sequim Campus."
keywords: Sequim, data, marine, water level, tide gauge

# Attribution
creator_country: USA
creator_email: mcrldata at pnnl.gov
creator_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
creator_institution_url: https://www.pnnl.gov/
creator_sector: other
creator_type: institution
creator_url: https://www.pnnl.gov/
institution: Pacific Northwest National Laboratory (PNNL)
publisher_country: USA
publisher_email: mcrldata at pnnl.gov
publisher_institution: Pacific Northwest National Laboratory (PNNL) - Sequim
publisher_url: https://www.pnnl.gov/

# Platform and Instrument
platform: pier
platform_name: mcrl_pier
platform_vocabulary: https://mmisw.org/ont/ioos/platform
instrument: In Situ/Laboratory Instruments > Gauges > Tide Gauges
instrument_vocabulary: GCMD Instrument Keywords #https://gcmd.earthdata.nasa.gov/KeywordViewer/
make_model: FMR-51 YSI-Nile
calibration_date: "2021-03-04"

# Geospatial and Time
geospatial_bounds: POINT(48.07928 -123.04512)
geospatial_bounds_crs: "EPSG:4326"
geospatial_bounds_vertical_crs: "EPSG:5703"
geospatial_vertical_positive: up
time_coverage_start: "2021-03-04"
time_coverage_resolution: "5:00"

# TODO: Can we delete these? Part of storage location and file name right now...
location_id: tide_gauge
dataset_name: mcrl_pier
qualifier: ysi_nile_1
temporal: 5min
data_level: a1
```

**Comment by maxwelllevin** [comment]
@jmcvey3 I think this would be a nice feature to add, and I can think of a few possible ways we could implement something like this and hook it in:

* Implement it as a json schema and configure VS Code to use this for `*dataset*.yaml` files
* Implement it as a separate library to validate a dictionary or xarray dataset and use it at runtime via a pydantic validator on the (ingest) pipeline class
* Add a CLI / tool in tsdat that lets you generate metadata requirements and export those to a file so it can be used via the mechanisms above

I'm open to other ideas too. What do you think?

**Comment by maxwelllevin** [comment]
@jmcvey3 No, we hadn't really discussed more about file naming conventions but I think the ultimate goal was to be completely flexible so users programs can use their naming conventions for their files.

For custom file naming and other custom storage support I think what we should do is have custom offshoots of our `FileSystem` storage class, where each offshoot hard codes the storage standards they want to enforce.

For the configuration options I think the approaches I outlined earlier are simplest.

Are there any other areas you can think of where we should consider updates to make the pipeline more compliant with other standards?
