### ISSUE TITLE
Improve transformation pipelines

### ISSUE THREAD

**Issue by maxwelllevin** [tsdat/tsdat#161]
The `TransformationPipeline` is a bit tricky to set up and use.

In my opinion, the documentation is pretty sparse relative to the volume of new features (required converters, transform params, pipeline triggers, installation instructions / platform support, QC changes, etc). Additionally, I think there may be ways of automating / cleaning up some of these new features; maybe some parameters can be inferred automatically, we could add new YAML schemas that know about the transformation parameters/functions, etc.

suggestions/ideas welcome from anyone who sees this

This issue will be used to track progress towards these goals.

- [x] Improve documentation for transformation pipelines & related functions
- [x] Improve transformation parameters

**Comment by jmcvey3** [comment]
A tutorial for the VAP pipeline is on my todo list, and I'm planning on using https://github.com/ME-Data-Pipeline-Software/sofar_spotter_pipelines. I'll put up real data for it on MHKDR soonish.

**Comment by maxwelllevin** [comment]
Documentation improved in #178 by @jmcvey3 and @maxwelllevin. Transform params were improved in #170 by @jmcvey3. Need to create schemas for vap pipeline parameters
