### ISSUE TITLE
Pint doesn't use CF standard unit names for units of "degrees"

### ISSUE THREAD

**Issue by jmcvey3** [tsdat/tsdat#177]
The pint python package uses a different shorthand for degree units than what's specified in most standards documents.

For example:
- Temperature: "degF" should be "degree_F", "degC" should be "degree_C", "degR" should be "degree_R"
- Direction: "deg" should be "degree"
- Lat/Lon: standard names should be "degrees_E/degrees_east", "degrees_N/degrees_north", or "degrees_T/degrees_true"

Should be relatively straightforward to convert the standard name to the pint name and back.

**Comment by maxwelllevin** [comment]
Maybe https://github.com/xarray-contrib/cf-xarray is the solution to all our problems
