### ISSUE TITLE
get_filename function replaces title to dataset's title

### ISSUE THREAD

**Issue by ekman-kaur** [tsdat/tsdat#219]
**Describe the bug**
Tsdat is failing to overwrite the value of title for saving a plot file. 
example code line: plot_file = get_filename(ds, title="wave_data_plots", extension="png")

In this case, the plot_file should have title wave_data_plots but its being set to "cdip.201.c1.20230706.180000.Directional wave and sea surface temperature measurements collected in situ by Datawell DWR-M3 directional buoy located near SCRIPPS NEARSHORE, CA from 2023/07/06 18:00:00 to 2024/07/29 22:56:40..png" where "Directional wave and sea surface temperature measurements collected in situ by Datawell DWR-M3 directional buoy located near SCRIPPS NEARSHORE, CA from 2023/07/06 18:00:00 to 2024/07/29 22:56:40." is dataset's title. 

![image](https://github.com/user-attachments/assets/75cab315-9f53-4729-b713-9f4d54876dd5)
![image](https://github.com/user-attachments/assets/a861b429-3057-4c06-978a-f875c704fe23)

FILENAME_TEMPLATE.substitute(substitutions) results in 'cdip.201.c1.20230706.180000.Directional wave and sea surface temperature measurements collected in situ by Datawell DWR-M3 directional buoy located near SCRIPPS NEARSHORE, CA from 2023/07/06 18:00:00 to 2024/07/29 22:56:40..png'

Repo: Ingest-Oracle 
Pipeline: CDIP
Test: test_cdip_pipeline_rt

Please include the full traceback message (if applicable):
```
E               FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\kaur770\\AppData\\Local\\Temp\\tmpi4xp7qye\\cdip.201.c1.20230706.180000.Directional wave and sea surface temperature measurements collected in situ by Datawell DWR-M3 directional buoy located near SCRIPPS NEARSHORE, CA from 2023\\07\\06 18:00:00 to 2024\\07\\29 22:56:40..png'
```

**Environment** 

- OS: Windows 11
- `tsdat`: 0.8.5

**Comment by maxwelllevin** [comment]
@ekman-kaur yep that looks to be a bug – the 'title' parameter is being overridden by the 'title' global attribute in the `xr.Dataset`. Should be the other way around. I'll work on a fix.

Also a quick note – this function shouldn't be used directly. At the moment the only intended use is in the `SplitNetcdfWriter` class, but even that is a bit of a hack tbh. Please use `self.get_ancillarly_filepath()` in your pipeline instead, as this function respects the `storage_root` path, any changes to the filename template from the storage config file, and it returns the full path to where the file should be saved. The `get_filename()` function returns only the filename part.
