### ISSUE TITLE
Update tutorials in the documentation

### ISSUE THREAD

**Issue by maxwellevin** [tsdat/tsdat#26]
**Is your feature request related to a problem? Please describe.**
The tutorials in the documentation don't reflect the current state of `tsdat` and its template repositories.

**Describe the solution you'd like**
The tutorials should be updated to reflect the progress that has been made in the core `tsdat` library and in the associated template repositories in the last few months.

**Describe alternatives you've considered**
N/A

**Additional context**
This issue is related to an email thread started by Sangkeun (Matt) Lee, in which it was noted that [this tutorial](https://tsdat.readthedocs.io/en/latest/tutorials/local_data_ingest.html) has some problems working right out of the box. Fixing that tutorial should be part of this task.

**Comment by maxwellevin** [comment]
Regarding the tutorial in question; it looks like there were a few issues:
- Tutorial says to use python 3.7+. Only python 3.8+ is supported at this point
- Tutorial says the only requirements are `tsdat`. We actually need to do `pip install -r requirements.txt`
- Link to data standards was broken
- Yaml was over-indented, and in one case the indentation was wrong (converter section for `time` in the pipeline config file).
- The data linked in the tutorial changed. There is no `Ice Accretion Source` variable anymore. The ingest needs to be updated to use different variables

**Comment by maxwellevin** [comment]
@jmcvey3 can you add a tutorial for the new ingest-template to the documentation?

**Comment by jmcvey3** [comment]
> @jmcvey3 can you add a tutorial for the new ingest-template to the documentation?

In progress

**Comment by maxwellevin** [comment]
This completed by @jmcvey3 in PR #40
