### ISSUE TITLE
raw_dataset_mapping variable type mismatch

### ISSUE THREAD

**Issue by kefeimo** [tsdat/tsdat#48]
**Describe the bug**
In tsdat 0.2.12
With the following code snippet (**note: use screenshot for syntax highlight to improve readability**)

<img width="336" alt="image" src="https://user-images.githubusercontent.com/28743873/163659466-d8b1e6c3-9772-405c-b9c1-84ea293120f0.png">

<img width="314" alt="image" src="https://user-images.githubusercontent.com/28743873/163659514-23adbadc-a2ba-4bba-87a4-557666802426.png">

The `raw_dataset_mapping` variable is defined as `Dict[str, xr.Dataset]`, while the `def read_and_persist_raw_files ` method outputs  `List[str]`. This is a type mismatch.

**Note: Later, `raw_dataset_mapping` is reassigned by `def hook_customize_raw_datasets`, which outputs `Dict[str, xr.Dataset]`. So if we don't consider immutability and try to reuse `raw_dataset_mapping`, then maybe consider using union or dropping the type annotation to avoid conflict.**

<img width="319" alt="image" src="https://user-images.githubusercontent.com/28743873/163659600-db23cc24-643f-460a-a4fa-26e1ae1cd0c1.png">

**To Reproduce**
(Minimal set of steps to reproduce the behavior:)
```
# Serch the following code snippet in /tsdat/pipeline/ingest_pipeline.py
raw_dataset_mapping: Dict[
                str, xr.Dataset
            ] = self.read_and_persist_raw_files(file_paths)
```

Please include the full Traceback message (if applicable):
```
Not applicable.
```

**Expected behavior**
(A clear and concise description of what you expected to happen.)
The annotation should match the actual type. Otherwise use the dynamic-type style (i.e., drop the annotation.)

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
See above.

**Comment by maxwellevin** [comment]
Hi @kefeimo, thanks for catching this. We definitely did not do the best job with type-checking for this version of tsdat. I'm currently working on a [major refactor](https://github.com/maxwellevin/tsdat/tree/v1) that will be 100% typed (or very close to it) which will resolve this issue and many more. I'll leave this issue open until I can get those changes merged in
