### ISSUE TITLE
Improve QCError interability

### ISSUE THREAD

**Issue by kefeimo** [tsdat/tsdat#50]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
<img width="494" alt="image" src="https://user-images.githubusercontent.com/28743873/163749603-ec57c3fc-9632-416c-9ae8-5f966092ba0c.png">
<img width="167" alt="image" src="https://user-images.githubusercontent.com/28743873/163750190-cdde6498-0ef8-4ee1-bd41-b994e0feb812.png">

Per the above images, when enable QC (quality control) and the QC detect repetitive timestamp throw the above error log. 
However, the error log only indicate the column that caused the error, not what type of error (i.e., "timestamp" need to be identical), or where the error happens (imaging it is a very long column it is almost impossible to debug or even notify what the root cause is.)

**Describe the solution you'd like**
(A clear and concise description of what you want to happen.)
- indicate what type of error it is
- indicate where the error happens (i.e., column + row)

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered.)
Utilize already existing underlying system's Exception mechanism. i.e., Pandas

**Additional context**
(Add any other context or screenshots about the feature request here.)
Use James's [ ingest-buoy repository](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fa2edap%2Fingest-buoy&data=04%7C01%7Ckefei.mo%40pnnl.gov%7C476c4279db59443f766308da19a423ed%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C637850490005708725%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FjH3Kb0Ccv1YbzQfsqViJ73vQfCZszW2hK%2FSQIBFedI%3D&reserved=0) to reproduce the error.

e.g., in `waves_morro` https://github.com/a2edap/ingest-buoy/tree/main/ingest/waves_morro, add a repetitive timestamp at the end, and run the test.
<img width="670" alt="image" src="https://user-images.githubusercontent.com/28743873/163750822-767e4d6c-aed3-4172-a046-76cc01ea8036.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/28743873/163750919-4136ba79-6e46-46fe-8048-fda76a61fc8c.png">

**Comment by kefeimo** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/28743873/163761222-6f4dd16c-7ebd-4346-a84f-038d1160bade.png">
The word "monotonicity" in "manage_coordinate_monotonicity" might give some clue, but monotonicity doesn't mean it has to be identical. Quote ref: [Monotonic function - Wikipedia](https://en.wikipedia.org/wiki/Monotonic_function#:~:text=defined%20on%20a%20subset%20of,it%20simply%20must%20not%20decrease.)
<img width="564" alt="image" src="https://user-images.githubusercontent.com/28743873/163761380-c25c5a68-e67d-4d9d-9a14-74c83e345dd0.png">

**Comment by maxwellevin** [comment]
@kefeimo Sorry, just getting to this now. This is good feedback. I think reworking this check could be worthwhile. Logging the actual failed values/indexes would be pretty helpful for debugging & manual inspection. I can probably take a look at this part later next week.

Regarding the naming... yeah.. I don't like it either. As you pointed out, the word monotonic implies that duplicates are allowed. The origins of our CheckMonotonic quality checker actually come from ARM, where they define monotonic as strictly increasing or strictly decreasing (no duplicates).

At this point I'm hesitant to change the default behavior of this check, but what we could do is add an 'allow_equal' or 'allow_duplicates' parameter to the CheckMonotonic class that would allow duplicates in the monotonic check. What do you think?

**Comment by kefeimo** [comment]
> 

I am not sure about the scope to rewrite monotonic check, and I would probably feel reluctant to touch it as well. My current thought is to write a time-duplicate-check method (maybe in a new time check class). And it might be easier to decouple data check based on data types, e.g., timestamp, numeric, non-numeric
