### ISSUE TITLE
Not sure how to turn on/enable QC (quality control)

### ISSUE THREAD

**Issue by kefeimo** [tsdat/tsdat#51]
**Is your feature request related to a problem? Please describe.**
(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])
As describe in issue #50, when QC is turned on, tsdat can detect repetitive timestamp. 
However, I am not sure where/how to turn on QC, especially using the ingetst-template. 
My guess is `data_level`, for example, in `pipeline_config_example_ingest_pnnl.yml` is where to configure qc on-and-off. As mentioned in the template and quote:
> data_level: "b1" # If not applying QC this should be set to "a1"

But I have tried both "b1" and "a1", and they both falsely passed the repetitive timestamp input data. So I am not sure what is the right way to enable QC functionality

**Describe the solution you'd like**
(A clear and concise description of what you want to happen.)
Would like to know how to turn on QC.

**Describe alternatives you've considered**
(A clear and concise description of any alternative solutions or features you've considered.)
Would like to know how to turn on QC.

**Additional context**
(Add any other context or screenshots about the feature request here.)
To reproduce the problem.
- Use the example project in ingest-template: https://github.com/tsdat/ingest-template/tree/main/ingest/example_ingest_pnnl
- add a repeated datetime/timestamp in the `data.csv`
  
<img width="388" alt="image" src="https://user-images.githubusercontent.com/28743873/163752174-74460ab0-2123-4094-9d34-2e5a76edb58c.png">

- run 'def test_example_ingest_pnnl_pipeline()` in `test_pipeline.py`
- I was expecting it would raise an error like in issue #50, but nothing happened.
- Note: I commented out `xr.testing.assert_allclose(output, expected)` for clarity.
  <img width="391" alt="image" src="https://user-images.githubusercontent.com/28743873/163752373-d7d87dbb-4be9-4c32-9107-add508462149.png">

**Comment by maxwellevin** [comment]
@kefeimo has this issue been resolved by improved documentation in the template repository or on https://tsdat.readthedocs.io?

**Comment by kefeimo** [comment]
My bad, totally ignored this. It is resolved. Thanks @maxwellevin
