### ISSUE TITLE
Add a `processing_interval` option

### ISSUE THREAD

**Issue by maxwellevin** [tsdat/tsdat#9]
A `processing_interval` option should be supported to allow users to dictate the maximum period of time in which each output file should span. Files that would surpass the `processing_interval`, if provided, should be split such that each individual file spans no more than the processing interval. 

e.g., if we have `processing_interval: "1d"` and an input file starting at 18:00 and ending at 06:00 36 hours later then we would produce the following files:

- 18:00 - 23:59 (day 1)
- 00:00 - 23:59 (day 2)
- 00:00 - 06:00 (day 3)

Some factors that may need more consideration: 
- Cases where processed data may already exist in storage – should data be combined into the same file?
- What `processing_intervals` should be allowed? May be tied in with questions of offsets – i.e. how do you know where the cutoff is relative to both the data you are processing now, and the data you have already 
- Where would this functionality live – pipeline, storage, or elsewhere?

**Comment by jmcvey3** [comment]
Could extend #105 to provide a solution to this enhancement.

**Comment by jmcvey3** [comment]
Keeping #105 to provide a solution for local storage. AWS S3 storage (#106) provides the opportunity to organize output data by specific time intervals
