### ISSUE TITLE
Optional dependencies

### ISSUE THREAD

**Issue by maxwelllevin** [tsdat/tsdat#95]
**Is your feature request related to a problem? Please describe.**
Tsdat requires a large number of dependencies out of the box. This makes installing tsdat slower than it needs to be and also presents challenges to users who need to review all dependencies.

**Describe the solution you'd like**
It would be nice if tsdat could exclude unnecessary dependencies by default (e.g., pyarrow and parquet dependencies, zarr dependencies, boto3, etc), but provide options to install them. Xarray does this quite nicely -- `pip install xarray` gets you the basics, `pip install "xarray[io]"` gives you the basics and additional libraries for io, etc. We should also do this.

**Describe alternatives you've considered**
An alternative is to keep tsdat/tsdat related to core tsdat functionality and package the classes that use extra dependencies separately. This is a valid approach, but I'd prefer to use it for supporting domain-specific requirements like a `tdms` file handler or `A2eStorage` class.

**Additional context**
This stems from a discussion with @kefeimo

**Comment by Chitrasivaraman** [comment]
Michael will talk to Max and define scope for this task.
